# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('url', models.URLField()),
                ('category', models.CharField(choices=[('naija', 'Nigerian'), ('foreign', 'Foreign')], max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=services.models.upload_image_path)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='services.Site')),
            ],
            options={
                'verbose_name': 'song',
                'verbose_name_plural': 'songs',
                'ordering': ('-timestamp',),
            },
        ),
    ]
