# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='site',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
