# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180120_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default='test', max_length=120),
            preserve_default=False,
        ),
    ]
