# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_song_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(default='unavailable', max_length=120),
        ),
    ]
