# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-19 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20180121_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('site', models.ManyToManyField(blank=True, related_name='subscribed', to='services.Site')),
            ],
        ),
    ]
