# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-23 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20180223_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='site',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscribed', to='services.Site'),
        ),
    ]
