# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-26 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20180225_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='category',
        ),
    ]
