# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_subscription_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('O', 'Ok'), ('E', 'Error'), ('R', 'Running')], default='O', max_length=1),
        ),
    ]
